# code: language=ansible
---
- name: Get service facts
  ansible.builtin.service_facts:

- when:
    - ansible_facts.services["gitea.service"] is defined
    - ansible_facts.services["gitea.service"].state == "running"
    - gitea_active_version.stdout != gitea_version
  block:
    - name: Stopping gitea before upgrade
      ansible.builtin.service:
        name: gitea
        state: stopped

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        mode: 'u=rwx,g=rx,o='
      with_items:
        - "{{ gitea_backup_location }}"

    - name: Backing up gitea before upgrade
      ansible.builtin.command:
        cmd: "/usr/local/bin/gitea dump -c /etc/gitea/gitea.ini"
        chdir: "{{ gitea_backup_location }}"
      become: true
      become_user: "{{ gitea_user }}"
