# code: language=ansible
---
- name: Configure gitea
  ansible.builtin.template:
    src: gitea.ini.j2
    dest: /etc/gitea/gitea.ini
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0400
  notify: "Restart gitea"

- name: Enable systemd service
  ansible.builtin.systemd:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
