# code: language=ansible
---
- name: Install systemd service
  become: true
  ansible.builtin.template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service
    owner: root
    group: root
    mode: 0644
  notify:
    - "Reload systemd"
    - "Restart gitea"

- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
