# code: language=ansible
---
- name: Gather installed packages for checks later on
  ansible.builtin.package_facts:
    manager: auto

- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', gitea_variables) }}"

- name: Gather versioning information
  ansible.builtin.import_tasks: versioncheck.yml

- name: Create gitea user and role
  ansible.builtin.import_tasks: create_user.yml
  become: true

- name: Install or update gitea
  ansible.builtin.import_tasks: install.yml

- name: Create directories
  ansible.builtin.import_tasks: directory.yml
  become: true

- name: Setup gitea systemd service
  ansible.builtin.include_tasks: install_systemd.yml
  when: ansible_service_mgr == "systemd"

- name: Generate JWT Secrets if undefined
  ansible.builtin.import_tasks: jwt_secrets.yml

- name: Generate gitea secrets if undefined
  ansible.builtin.import_tasks: gitea_secrets.yml
  become: true

- name: Configure gitea
  ansible.builtin.import_tasks: configure.yml
  become: true
